### ISSUE TITLE
when to release the code?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [AI-Zhpp/HAT#1]
when to release the code?

**Comment by ShihuaHuang95** [comment]
Same question.

**Comment by AI-Zhpp** [comment]
Thanks for you interest. Now, we have released the code. Any problems, please contact me freely.

**Comment by AI-Zhpp** [comment]
> 
> 
> Same question.

Thanks for your interest. Now, we have released the code. Any problems, please contact me freely.

**Comment by zimenglan-sysu-512** [comment]
why not put the code in github?

**Comment by AI-Zhpp** [comment]
> why not put the code in github?
